//! A panel that lists the objects that can be inspected in the current view,
//! typically shown on the left side of the inspector.
//!
//! See [`ObjectListTab`] for the different tabs available in this panel,
//! which is used to switch between different object types (e.g., entities, resources).
//!
//! # UI Hierarchy
//!
//! The main container for this panel is an entity with the [`ObjectListPanel`] component.
//! This entity is a [`Node`] which is a parent for all of the UI nodes related
//! to the object list panel, including tabs, search bar, and list content.
//!
//! The content for each tab is stored in a child node with the [`ObjectListContent`] component,
//! which has a field indicating which tab it belongs to. These content nodes are typically scrollable
//! areas which contain the list of entities or resources, and are switched between using the tab buttons.
//!
//! Each row in the object list is an entity with the [`ObjectRow`] component, which
//! stores the object this row represents (e.g., an entity or resource ID).
//! These rows are children of the content node for their respective tab.
//!
//! The search bar is an entity with the [`SearchInput`] component, which is a child of the main [`ObjectListPanel`] node.
//!
//! # Data flow
//!
//! The list of objects to display in this panel is generated by the [`update_inspector_cache`] system,
//! which stores the generated list in the [`InspectorCache`] resource. The [`render_object_list`] system then reads from this cache
//! and spawns UI nodes for each object in the list, as children of the appropriate content node based on the active tab.
//!
//! When a tab is activated via the [`TabActivated`] event, the [`update_active_objects_tab_on_activate_tab`] system
//! updates the active tab in the [`InspectorState`]. This then triggers a refresh of the object list display to
//! show the appropriate objects for the selected tab.
//!
//! Clicking on an object row sends an [`Activate`] event,
//! which is observed by the [`on_object_row_click`] system to update the selected object in the [`InspectorState`].
//! This allows the [`detail_panel`](super::detail_panel) to show the appropriate information for the selected object.

use bevy::ecs::component::ComponentId;
use bevy::ecs::hierarchy::ChildSpawnerCommands;
use bevy::ecs::observer::On;

use bevy::ecs::resource::IsResource;
use bevy::ecs::system::SystemIdMarker;
use bevy::feathers::controls::{ButtonProps, button};
use bevy::prelude::*;
use bevy::ui::Val::*;
use bevy::ui_widgets::{Activate, ControlOrientation, CoreScrollbarThumb, Scrollbar};
use core::any::TypeId;

use crate::entity_grouping::{EntityGrouping, GroupingStrategy};
use crate::extension_methods::WorldInspectionExtensionTrait;
use crate::gui::config::InspectorConfig;
use crate::gui::state::{
    InspectorCache, InspectorInternal, InspectorState, ObjectListEntry, ObjectListTab,
    WorldSnapshot,
};
use crate::gui::widgets::tabs::{HasContent, Tab, TabActivated, TabContentDisplayMode, TabGroup};
use crate::inspection::component_inspection::{ComponentInspectionSettings, ComponentMetadataMap};
use crate::inspection::entity_inspection::{
    EntityInspection, EntityInspectionError, EntityInspectionSettings,
    MultipleEntityInspectionSettings,
};
use crate::memory_size::MemorySize;

/// Marker component for the object list panel container.
///
/// This entity entity is a [`Node`] which is a parent for all of the UI nodes related to the object list panel,
/// including tabs, search bar, and list content.
#[derive(Component)]
pub struct ObjectListPanel;

/// Marker component for the [`Node`] which holds the content in each tab of the object list panel.
///
/// These contents are typically scrollable areas which contain the list of entities or resources, and are switched between using the tab buttons.
#[derive(Component)]
pub struct ObjectListContent {
    pub tab: ObjectListTab,
}

/// Marker component for object rows, which stores the object this row represents.
#[derive(Component)]
pub struct ObjectRow {
    pub selected_object: Entity,
}

/// Marker component for the search bar input.
#[derive(Component)]
pub struct SearchInput;

/// Criteria used to filter objects in both paused and running modes.
struct ObjectListFilter {
    tab: ObjectListTab,
    text: String,
    mandatory_components: Vec<ComponentId>,
}

/// Allows abstracting over paused and running mode
/// for checking component presence.
trait ComponentChecker {
    fn has_component<T: Component>(&self) -> bool;
}

impl<'w> ComponentChecker for EntityRef<'w> {
    fn has_component<T: Component>(&self) -> bool {
        self.contains::<T>()
    }
}

impl ComponentChecker for (&EntityInspection, &ComponentMetadataMap) {
    fn has_component<T: Component>(&self) -> bool {
        let inspection: &EntityInspection = self.0;
        let type_id = TypeId::of::<T>();
        let metadata_map: &ComponentMetadataMap = self.1;
        if let Some(components) = &inspection.components {
            for comp in components {
                if let Some(metadata) = metadata_map.map.get(&comp.component_id)
                    && metadata.type_id == Some(type_id)
                {
                    return true;
                }
            }
        }
        false
    }
}

/// Exclusive system that refreshes the [`InspectorCache`].
/// We can't sensibly cache results from one call to the next,
/// as the world may have changed substantially in between.
///
/// Uses exclusive world access to avoid resource conflicts.
pub fn update_inspector_cache(world: &mut World) {
    update_component_metadata_map(world);
    let (is_paused, selected_object, filter) = {
        let state = world.resource::<InspectorState>();
        (
            state.is_paused,
            state.selected_object,
            ObjectListFilter {
                tab: state.active_objects_tab,
                text: state.filter_text.clone(),
                mandatory_components: state.mandatory_components.clone(),
            },
        )
    };

    if is_paused {
        update_cache_paused(world, &filter);
    } else {
        update_cache_running(world, selected_object, &filter);
    }
}

fn update_component_metadata_map(world: &mut World) {
    world.resource_scope(|world, mut inspector_cache: Mut<InspectorCache>| {
        let metadata_map = match inspector_cache.metadata_map.take() {
            Some(mut metadata_map) => {
                metadata_map.update(world);
                metadata_map
            }
            None => ComponentMetadataMap::generate(world),
        };
        inspector_cache.metadata_map = Some(metadata_map);
    });
}

fn update_cache_running(
    world: &mut World,
    selected_object: Option<Entity>,
    filter: &ObjectListFilter,
) {
    let object_list = generate_live_object_list(world, filter);
    let updated_snapshot = if let Some(selected) = selected_object {
        WorldSnapshot::single(world, selected)
    } else {
        WorldSnapshot::empty()
    };

    let mut cache = world.resource_mut::<InspectorCache>();
    cache.snapshot = updated_snapshot;
    cache.filtered_objects = object_list;
}

fn generate_live_object_list(world: &mut World, filter: &ObjectListFilter) -> Vec<ObjectListEntry> {
    let entities = query_entities_for_tab(world, filter.tab);
    let inspections = inspect_entities(world, &filter.mandatory_components, entities);

    filter_inspections_and_create_entries(
        inspections.iter().filter_map(|r| r.as_ref().ok()),
        filter,
        None,
    )
}

/// Queries all entities matching the active tab, excluding UI nodes, windows, and inspector internals.
fn query_entities_for_tab(world: &mut World, tab: ObjectListTab) -> Vec<Entity> {
    // TODO: This should include UI nodes and windows, as long as they're not spawned by the inspector
    let mut query = world.query::<EntityRef>();
    query
        .iter(world)
        .filter(|e| {
            if e.contains::<InspectorInternal>() {
                return false;
            }
            matches_tab(*e, tab)
        })
        .map(|e| e.id())
        .collect()
}

fn inspect_entities(
    world: &mut World,
    mandatory_components: &[ComponentId],
    entities: Vec<Entity>,
) -> Vec<Result<EntityInspection, EntityInspectionError>> {
    world.resource_scope(|world, mut cache: Mut<InspectorCache>| {
        let Some(ref mut metadata_map) = cache.metadata_map else {
            return Vec::new();
        };
        let inspection_settings = MultipleEntityInspectionSettings {
            with_component_filter: mandatory_components.to_vec(),
            ..default()
        };
        world.inspect_multiple(entities.iter().copied(), inspection_settings, metadata_map)
    })
}

fn update_cache_paused(world: &mut World, filter: &ObjectListFilter) {
    let (has_full_snapshot, cache_is_dirty) = {
        let cache = world.resource::<InspectorCache>();
        (cache.snapshot.is_full(), cache.is_dirty)
    };
    if !has_full_snapshot || cache_is_dirty {
        info!("<!!!> Dirty cache, updating snapshot.");
        create_full_snapshot(world);
    }

    world.resource_scope(|_world, mut cache: Mut<InspectorCache>| {
        let object_list = filter_inspections_and_create_entries(
            cache.snapshot.iter(),
            filter,
            cache.metadata_map.as_ref(),
        );
        cache.filtered_objects = object_list;
        cache.is_dirty = false;
    });
}

fn create_full_snapshot(world: &mut World) {
    let entities_to_snapshot = get_all_inspectable_entities(world);
    // Ensures consistent entity ordering in paused mode.
    let sorted_entities =
        EntityGrouping::generate(world, entities_to_snapshot, GroupingStrategy::Hierarchy)
            .flatten();

    let metadata_map = world
        .resource_mut::<InspectorCache>()
        .metadata_map
        .take()
        .unwrap();
    let settings = EntityInspectionSettings {
        include_components: true,
        component_settings: ComponentInspectionSettings {
            store_reflected_value: true,
            ..default()
        },
    };

    let mut inspections = Vec::new();
    for entity in &sorted_entities {
        let inspection = world.inspect_cached(*entity, &settings, &metadata_map);
        if let Ok(inspection) = inspection {
            inspections.push(inspection);
        }
    }

    let mut cache = world.resource_mut::<InspectorCache>();
    cache.metadata_map = Some(metadata_map);
    cache.snapshot = WorldSnapshot::full(inspections, sorted_entities);
}

/// Gets all the entities without the component [`InspectorInternal`].
fn get_all_inspectable_entities(world: &mut World) -> Vec<Entity> {
    let mut query = world.query::<EntityRef>();
    query
        .iter(world)
        .filter(|e| !e.contains::<InspectorInternal>())
        .map(|e| e.id())
        .collect()
}

fn filter_inspections_and_create_entries<'a>(
    inspections: impl Iterator<Item = &'a EntityInspection>,
    filter: &ObjectListFilter,
    metadata_map: Option<&ComponentMetadataMap>,
) -> Vec<ObjectListEntry> {
    inspections
        .filter(|inspection| {
            if let Some(metadata_map) = metadata_map {
                if !matches_tab((*inspection, metadata_map), filter.tab) {
                    return false;
                }

                if !filter
                    .mandatory_components
                    .iter()
                    .all(|&comp_id| has_component_by_id(inspection, comp_id))
                {
                    return false;
                }
            }
            true
        })
        .filter_map(|inspection| try_create_object_list_entry(inspection, &filter.text))
        .collect()
}

fn try_create_object_list_entry(
    inspection: &EntityInspection,
    filter_text: &str,
) -> Option<ObjectListEntry> {
    let name = inspection
        .name
        .as_ref()
        .map(|n| n.to_string())
        .unwrap_or_else(|| format!("Entity {:?}", inspection.entity));

    if !filter_text.is_empty() && !name.to_lowercase().contains(&filter_text.to_lowercase()) {
        return None;
    }

    Some(ObjectListEntry {
        entity: inspection.entity,
        display_name: name,
        component_count: inspection.components.as_ref().map(|c| c.len()).unwrap_or(0),
        memory_size: inspection.total_memory_size.unwrap_or(MemorySize::new(0)),
    })
}

fn matches_tab(checker: impl ComponentChecker, tab: ObjectListTab) -> bool {
    match tab {
        ObjectListTab::Entities => {
            !checker.has_component::<Node>()
                && !checker.has_component::<IsResource>()
                && !checker.has_component::<Observer>()
                && !checker.has_component::<SystemIdMarker>()
        }
        ObjectListTab::Resources => checker.has_component::<IsResource>(),
        // TODO: This inspector generates its own observers, which should be excluded
        // using InspectorInternal
        ObjectListTab::Observers => checker.has_component::<Observer>(),
        ObjectListTab::OneShotSystems => checker.has_component::<SystemIdMarker>(),
    }
}

fn has_component_by_id(inspection: &EntityInspection, component_id: ComponentId) -> bool {
    if let Some(components) = &inspection.components {
        for comp in components {
            if comp.component_id == component_id {
                return true;
            }
        }
    }
    false
}

/// System that syncs the object list display with the cache.
pub fn render_object_list(
    mut commands: Commands,
    cache: Res<InspectorCache>,
    state: Res<InspectorState>,
    config: Res<InspectorConfig>,
    list_content: Query<(Entity, &ObjectListContent)>,
    children: Query<&Children>,
) {
    for (content_entity, object_list_content) in &list_content {
        if state.active_objects_tab != object_list_content.tab {
            continue;
        }

        // Clear existing rows
        // TODO: can we reuse existing rows instead of despawning all?
        if let Ok(children) = children.get(content_entity) {
            for child in children {
                commands.entity(*child).despawn();
            }
        }

        // Spawn new rows
        commands.entity(content_entity).with_children(|list| {
            for entry in &cache.filtered_objects {
                let is_selected = state.selected_object == Some(entry.entity());
                spawn_object_row(list, entry, is_selected, &config);
            }
        });
    }
}

/// Spawns a single object row button.
fn spawn_object_row(
    parent: &mut ChildSpawnerCommands<'_>,
    entry: &ObjectListEntry,
    is_selected: bool,
    config: &InspectorConfig,
) {
    // Truncate long names
    let display_name = entry.display_name();

    let display_name = if display_name.len() > 20 {
        format!("{}...", &display_name[..17])
    } else {
        display_name.to_string()
    };

    let ObjectListEntry {
        component_count,
        memory_size,
        ..
    } = entry;

    let label = format!(
        "{:20} {} comp | {}",
        display_name, component_count, memory_size
    );

    parent.spawn((button(
        ButtonProps::default(),
        ObjectRow {
            selected_object: entry.entity(),
        },
        bevy::prelude::Spawn((
            Text::new(label),
            TextFont {
                font_size: FontSize::Px(config.small_font_size),
                ..default()
            },
            TextColor(if is_selected {
                Color::WHITE
            } else {
                Color::srgba(0.9, 0.9, 0.9, 1.0)
            }),
        )),
    ),));
}

/// Observes [`TabActivated`] events to update the active objects tab
/// in the [`InspectorState`].
pub fn update_active_objects_tab_on_activate_tab(
    on_activate_tab: On<TabActivated>,
    has_contents: Query<&HasContent, With<Tab>>,
    object_list_contents: Query<&ObjectListContent>,
    children: Query<&Children>,
    mut state: ResMut<InspectorState>,
    mut writer: MessageWriter<RefreshObjectList>,
    mut ui_writer: MessageWriter<RefreshUI>,
    mut commands: Commands,
) {
    let event = on_activate_tab.event();
    if let Ok(has_content) = has_contents.get(event.tab) {
        let content_parent_entity = has_content.0;
        if let Ok(children) = children.get(content_parent_entity) {
            for child in children {
                if let Ok(object_list_content) = object_list_contents.get(*child) {
                    let object_list_tab = object_list_content.tab;

                    state.active_objects_tab = object_list_tab;
                    if state.is_paused {
                        // Updating the filter allows the new tab content to show the right content
                        //
                        // NOTE: This solution is a bit hacky,
                        // but it's currently needed to not disrupt
                        // the current exclusive system centric code structure.
                        commands.queue(|world: &mut World| update_inspector_cache(world));
                        ui_writer.write(RefreshUI);
                    } else {
                        // Forced UI sync to avoid showing stale state.
                        writer.write(RefreshObjectList);
                    }
                    return;
                }
            }
        }
    }
}

/// Global observer for object row clicks.
/// Added in [`InspectorWindowPlugin`](crate::gui::plugin::InspectorWindowPlugin).
///
/// Traverses up the parent hierarchy to find the [`ObjectRow`] component.
pub fn on_object_row_click(
    activate: On<Activate>,
    mut state: ResMut<InspectorState>,
    rows: Query<&ObjectRow>,
    mut writer: MessageWriter<RefreshObjectList>,
    mut ui_writer: MessageWriter<RefreshUI>,
) {
    if let Ok(row) = rows.get(activate.entity) {
        state.selected_object = Some(row.selected_object);
        if !state.is_paused {
            writer.write(RefreshObjectList);
        } else {
            ui_writer.write(RefreshUI);
        }
    }
}

/// Spawns the object list panel structure.
pub fn spawn_object_list_panel(parent: &mut ChildSpawnerCommands<'_>, config: &InspectorConfig) {
    parent
        .spawn((
            Node {
                width: config.left_panel_width,
                height: Percent(100.0),
                display: Display::Flex,
                flex_direction: FlexDirection::Column,
                border: UiRect::all(Px(1.0)),
                ..default()
            },
            BorderColor::all(config.border_color),
            ObjectListPanel,
        ))
        .with_children(|panel| {
            // Tab buttons
            let entities_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("Entities"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let resources_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("Resources"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let observers_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("Observers"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let one_shot_systems_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("One-Shot systems"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let _tab_group_entity = panel
                .spawn((
                    Node {
                        width: Percent(100.0),
                        height: config.tab_bar_height,
                        border: UiRect::bottom(Px(1.0)),
                        // Space out tab items
                        justify_content: JustifyContent::SpaceEvenly,
                        align_items: AlignItems::Center,
                        ..default()
                    },
                    BorderColor::all(config.border_color),
                    TabGroup::new(Some(entities_tab_entity)),
                ))
                .add_children(&[
                    entities_tab_entity,
                    resources_tab_entity,
                    observers_tab_entity,
                    one_shot_systems_tab_entity,
                ])
                .id();

            // Search bar placeholder
            panel
                .spawn((
                    Node {
                        width: Percent(100.0),
                        padding: config.panel_padding,
                        border: UiRect::bottom(Px(1.0)),
                        ..default()
                    },
                    BorderColor::all(config.border_color),
                    SearchInput,
                ))
                .with_children(|search| {
                    search.spawn((
                        Text::new("Search..."),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                        TextColor(config.muted_text_color),
                    ));
                });

            panel
                .spawn(Node {
                    display: Display::Flex,
                    flex_direction: FlexDirection::Column,
                    flex_grow: 1.0,
                    ..default()
                })
                .with_children(|content_panels_container| {
                    let entities_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::Entities,
                        Display::Grid,
                    );
                    let resources_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::Resources,
                        Display::None,
                    );
                    let observers_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::Observers,
                        Display::None,
                    );
                    let one_shot_systems_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::OneShotSystems,
                        Display::None,
                    );
                    content_panels_container
                        .commands()
                        .entity(entities_tab_entity)
                        .insert((
                            HasContent(entities_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                    content_panels_container
                        .commands()
                        .entity(resources_tab_entity)
                        .insert((
                            HasContent(resources_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                    content_panels_container
                        .commands()
                        .entity(observers_tab_entity)
                        .insert((
                            HasContent(observers_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                    content_panels_container
                        .commands()
                        .entity(one_shot_systems_tab_entity)
                        .insert((
                            HasContent(one_shot_systems_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                });
        });
}

fn scrollable_area(
    parent: &mut ChildSpawnerCommands<'_>,
    config: &InspectorConfig,
    tab: ObjectListTab,
    display: Display,
) -> Entity {
    let scrollbar_width = 8.0;
    parent
        .spawn(Node {
            width: Percent(100.0),
            flex_grow: 1.0,
            display,
            grid_template_columns: vec![GridTrack::fr(1.0), GridTrack::px(scrollbar_width)],
            ..default()
        })
        .with_children(|scroll_area| {
            // Scroll content
            let content_id = scroll_area
                .spawn((
                    Node {
                        display: Display::Flex,
                        flex_direction: FlexDirection::Column,
                        row_gap: config.item_gap,
                        padding: config.panel_padding,
                        overflow: Overflow::scroll_y(),
                        ..default()
                    },
                    ScrollPosition::default(),
                    ObjectListContent { tab },
                ))
                .id();

            // Scrollbar
            scroll_area
                .spawn((
                    Scrollbar {
                        target: content_id,
                        orientation: ControlOrientation::Vertical,
                        min_thumb_length: 20.0,
                    },
                    Node {
                        width: Px(scrollbar_width),
                        height: Percent(100.0),
                        ..default()
                    },
                    BackgroundColor(Color::srgba(0.15, 0.15, 0.15, 0.5)),
                ))
                .with_children(|sb| {
                    sb.spawn((
                        CoreScrollbarThumb,
                        Node {
                            width: Percent(100.0),
                            ..default()
                        },
                        BackgroundColor(Color::srgba(0.5, 0.5, 0.5, 0.8)),
                    ));
                });
        })
        .id()
}

/// A message that drives a refresh of the object list panel.
///
/// This will cause the system sets [`RefreshCache`] and [`SyncUI`] to run when seen,
/// via the use of run conditions added as part of [`InspectorWindowPlugin`](crate::gui::plugin::InspectorWindowPlugin).
///
/// This is a public message to allow users to trigger (or cancel!) refreshes manually if desired.
///
/// [`RefreshCache`]: crate::gui::plugin::InspectorSet::RefreshCache
/// [`SyncUI`]: crate::gui::plugin::InspectorSet::SyncUI
#[derive(Message)]
pub struct RefreshObjectList;

/// A message that drives a refresh of the UI panels,
/// without forcing a cache rebuild.
#[derive(Message)]
pub struct RefreshUI;

/// A system which periodically sends a [`RefreshObjectList`] message.
///
/// The frequency is controlled by the `refresh_interval` field in [`InspectorConfig`].
pub fn refresh_object_list_periodically(
    mut message_writer: MessageWriter<RefreshObjectList>,
    time: Res<Time>,
    mut timer: Local<Timer>,
    mut is_timer_ticking: Local<bool>,
    config: Res<InspectorConfig>,
    state: Res<InspectorState>,
) {
    // Disable auto-refreshing in certain conditions.
    if config.refresh_interval.is_none() || state.is_paused {
        *is_timer_ticking = false;
        return;
    }

    // Initialize timer if needed
    if timer.duration().is_zero() {
        *timer = Timer::new(config.refresh_interval.unwrap(), TimerMode::Repeating);
    }

    if !*is_timer_ticking {
        *is_timer_ticking = true;
        timer.reset();
    }

    // Tick timer
    timer.tick(time.delta());

    // Send message if timer finished
    if timer.just_finished() {
        message_writer.write(RefreshObjectList);
    }
}
