//! A panel that lists the objects that can be inspected in the current view,
//! typically shown on the left side of the inspector.
//!
//! See [`ObjectListTab`] for the different tabs available in this panel,
//! which is used to switch between different object types (e.g., entities, resources).
//!
//! # UI Hierarchy
//!
//! The main container for this panel is an entity with the [`ObjectListPanel`] component.
//! This entity is a [`Node`] which is a parent for all of the UI nodes related
//! to the object list panel, including tabs, search bar, and list content.
//!
//! The content for each tab is stored in a child node with the [`ObjectListContent`] component,
//! which has a field indicating which tab it belongs to. These content nodes are typically scrollable
//! areas which contain the list of entities or resources, and are switched between using the tab buttons.
//!
//! Each row in the object list is an entity with the [`ObjectRow`] component, which
//! stores the object this row represents (e.g., an entity or resource ID).
//! These rows are children of the content node for their respective tab.
//!
//! The search bar is an entity with the [`SearchInput`] component, which is a child of the main [`ObjectListPanel`] node.
//!
//! # Data flow
//!
//! The list of objects to display in this panel is generated by the [`update_inspector_cache`] system,
//! which stores the generated list in the [`InspectorCache`] resource. The [`render_object_list`] system then reads from this cache
//! and spawns UI nodes for each object in the list, as children of the appropriate content node based on the active tab.
//!
//! When a tab is activated via the [`TabActivated`] event, the [`update_active_objects_tab_on_tab_activated`] system
//! updates the active tab in the [`InspectorState`]. This then triggers a refresh of the object list display to
//! show the appropriate objects for the selected tab.
//!
//! Clicking on an object row sends an [`Activate`] event,
//! which is observed by the [`on_object_row_click`] system to update the selected object in the [`InspectorState`].
//! This allows the [`detail_panel`](super::detail_panel) to show the appropriate information for the selected object.

use bevy::ecs::hierarchy::ChildSpawnerCommands;
use bevy::ecs::observer::On;

use bevy::feathers::controls::{ButtonProps, button};
use bevy::prelude::*;
use bevy::ui::Val::*;
use bevy::ui_widgets::{Activate, ControlOrientation, CoreScrollbarThumb, Scrollbar};

use crate::gui::cache::{InspectorCache, update_inspector_cache};
use crate::gui::config::InspectorConfig;
use crate::gui::state::{InspectorState, ObjectListEntry, ObjectListTab};
use crate::gui::widgets::tabs::{HasContent, Tab, TabActivated, TabContentDisplayMode, TabGroup};

/// Marker component for the object list panel container.
///
/// This entity entity is a [`Node`] which is a parent for all of the UI nodes related to the object list panel,
/// including tabs, search bar, and list content.
#[derive(Component)]
pub struct ObjectListPanel;

/// Marker component for the [`Node`] which holds the content in each tab of the object list panel.
///
/// These contents are typically scrollable areas which contain the list of entities or resources, and are switched between using the tab buttons.
#[derive(Component)]
pub struct ObjectListContent {
    pub tab: ObjectListTab,
}

/// Marker component for object rows, which stores the object this row represents.
#[derive(Component)]
pub struct ObjectRow {
    pub selected_object: Entity,
}

/// Marker component for the search bar input.
#[derive(Component)]
pub struct SearchInput;

/// System that syncs the object list display with the cache.
pub fn render_object_list(
    mut commands: Commands,
    cache: Res<InspectorCache>,
    state: Res<InspectorState>,
    config: Res<InspectorConfig>,
    list_content: Query<(Entity, &ObjectListContent)>,
    children: Query<&Children>,
) {
    for (content_entity, object_list_content) in &list_content {
        if state.active_objects_tab != object_list_content.tab {
            continue;
        }

        // Clear existing rows
        // TODO: can we reuse existing rows instead of despawning all?
        if let Ok(children) = children.get(content_entity) {
            for child in children {
                commands.entity(*child).despawn();
            }
        }

        // Spawn new rows
        commands.entity(content_entity).with_children(|list| {
            for entry in &cache.filtered_objects {
                let is_selected = state.selected_object == Some(entry.entity());
                spawn_object_row(list, entry, is_selected, &config);
            }
        });
    }
}

/// Spawns a single object row button.
fn spawn_object_row(
    parent: &mut ChildSpawnerCommands<'_>,
    entry: &ObjectListEntry,
    is_selected: bool,
    config: &InspectorConfig,
) {
    // Truncate long names
    let display_name = entry.display_name();

    let display_name = if display_name.len() > 20 {
        format!("{}...", &display_name[..17])
    } else {
        display_name.to_string()
    };

    let ObjectListEntry {
        component_count,
        memory_size,
        ..
    } = entry;

    let label = format!(
        "{:20} {} comp | {}",
        display_name, component_count, memory_size
    );

    parent.spawn((button(
        ButtonProps::default(),
        ObjectRow {
            selected_object: entry.entity(),
        },
        bevy::prelude::Spawn((
            Text::new(label),
            TextFont {
                font_size: FontSize::Px(config.small_font_size),
                ..default()
            },
            TextColor(if is_selected {
                Color::WHITE
            } else {
                Color::srgba(0.9, 0.9, 0.9, 1.0)
            }),
        )),
    ),));
}

/// Observes [`TabActivated`] events to update the active objects tab
/// in the [`InspectorState`].
pub fn update_active_objects_tab_on_tab_activated(
    on_activate_tab: On<TabActivated>,
    has_contents: Query<&HasContent, With<Tab>>,
    object_list_contents: Query<&ObjectListContent>,
    children: Query<&Children>,
    mut state: ResMut<InspectorState>,
    mut writer: MessageWriter<RefreshCache>,
    mut ui_writer: MessageWriter<RefreshUI>,
    mut commands: Commands,
) {
    let event = on_activate_tab.event();
    if let Ok(has_content) = has_contents.get(event.tab) {
        let content_parent_entity = has_content.0;
        if let Ok(children) = children.get(content_parent_entity) {
            for child in children {
                if let Ok(object_list_content) = object_list_contents.get(*child) {
                    let object_list_tab = object_list_content.tab;

                    state.active_objects_tab = object_list_tab;
                    if state.is_paused {
                        // Updating the filter allows the new tab content to show the right content
                        //
                        // NOTE: This solution is a bit hacky,
                        // but it's currently needed to not disrupt
                        // the current exclusive system centric code structure.
                        commands.queue(|world: &mut World| update_inspector_cache(world));
                        ui_writer.write(RefreshUI);
                    } else {
                        // Forced UI sync to avoid showing stale state.
                        writer.write(RefreshCache);
                    }
                    return;
                }
            }
        }
    }
}

/// Global observer for object row clicks.
/// Added in [`InspectorWindowPlugin`](crate::gui::plugin::InspectorWindowPlugin).
///
/// Traverses up the parent hierarchy to find the [`ObjectRow`] component.
pub fn on_object_row_click(
    activate: On<Activate>,
    mut state: ResMut<InspectorState>,
    rows: Query<&ObjectRow>,
    mut writer: MessageWriter<RefreshCache>,
    mut ui_writer: MessageWriter<RefreshUI>,
) {
    if let Ok(row) = rows.get(activate.entity) {
        state.selected_object = Some(row.selected_object);
        if !state.is_paused {
            writer.write(RefreshCache);
        } else {
            ui_writer.write(RefreshUI);
        }
    }
}

/// Spawns the object list panel structure.
pub fn spawn_object_list_panel(parent: &mut ChildSpawnerCommands<'_>, config: &InspectorConfig) {
    parent
        .spawn((
            Node {
                width: config.left_panel_width,
                height: Percent(100.0),
                display: Display::Flex,
                flex_direction: FlexDirection::Column,
                border: UiRect::all(Px(1.0)),
                ..default()
            },
            BorderColor::all(config.border_color),
            ObjectListPanel,
        ))
        .with_children(|panel| {
            // Tab buttons
            let entities_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("Entities"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let resources_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("Resources"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let observers_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("Observers"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let one_shot_systems_tab_entity = panel
                .commands()
                .spawn(button(
                    ButtonProps::default(),
                    Tab,
                    bevy::prelude::Spawn((
                        Text::new("One-Shot systems"),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                    )),
                ))
                .id();
            let _tab_group_entity = panel
                .spawn((
                    Node {
                        width: Percent(100.0),
                        height: config.tab_bar_height,
                        border: UiRect::bottom(Px(1.0)),
                        // Space out tab items
                        justify_content: JustifyContent::SpaceEvenly,
                        align_items: AlignItems::Center,
                        ..default()
                    },
                    BorderColor::all(config.border_color),
                    TabGroup::new(Some(entities_tab_entity)),
                ))
                .add_children(&[
                    entities_tab_entity,
                    resources_tab_entity,
                    observers_tab_entity,
                    one_shot_systems_tab_entity,
                ])
                .id();

            // Search bar placeholder
            panel
                .spawn((
                    Node {
                        width: Percent(100.0),
                        padding: config.panel_padding,
                        border: UiRect::bottom(Px(1.0)),
                        ..default()
                    },
                    BorderColor::all(config.border_color),
                    SearchInput,
                ))
                .with_children(|search| {
                    search.spawn((
                        Text::new("Search..."),
                        TextFont {
                            font_size: FontSize::Px(config.body_font_size),
                            ..default()
                        },
                        TextColor(config.muted_text_color),
                    ));
                });

            panel
                .spawn(Node {
                    display: Display::Flex,
                    flex_direction: FlexDirection::Column,
                    flex_grow: 1.0,
                    ..default()
                })
                .with_children(|content_panels_container| {
                    let entities_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::Entities,
                        Display::Grid,
                    );
                    let resources_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::Resources,
                        Display::None,
                    );
                    let observers_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::Observers,
                        Display::None,
                    );
                    let one_shot_systems_list_entity = scrollable_area(
                        content_panels_container,
                        config,
                        ObjectListTab::OneShotSystems,
                        Display::None,
                    );
                    content_panels_container
                        .commands()
                        .entity(entities_tab_entity)
                        .insert((
                            HasContent(entities_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                    content_panels_container
                        .commands()
                        .entity(resources_tab_entity)
                        .insert((
                            HasContent(resources_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                    content_panels_container
                        .commands()
                        .entity(observers_tab_entity)
                        .insert((
                            HasContent(observers_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                    content_panels_container
                        .commands()
                        .entity(one_shot_systems_tab_entity)
                        .insert((
                            HasContent(one_shot_systems_list_entity),
                            TabContentDisplayMode(Display::Grid),
                        ));
                });
        });
}

fn scrollable_area(
    parent: &mut ChildSpawnerCommands<'_>,
    config: &InspectorConfig,
    tab: ObjectListTab,
    display: Display,
) -> Entity {
    let scrollbar_width = 8.0;
    parent
        .spawn(Node {
            width: Percent(100.0),
            flex_grow: 1.0,
            display,
            grid_template_columns: vec![GridTrack::fr(1.0), GridTrack::px(scrollbar_width)],
            ..default()
        })
        .with_children(|scroll_area| {
            // Scroll content
            let content_id = scroll_area
                .spawn((
                    Node {
                        display: Display::Flex,
                        flex_direction: FlexDirection::Column,
                        row_gap: config.item_gap,
                        padding: config.panel_padding,
                        overflow: Overflow::scroll_y(),
                        ..default()
                    },
                    ScrollPosition::default(),
                    ObjectListContent { tab },
                ))
                .id();

            // Scrollbar
            scroll_area
                .spawn((
                    Scrollbar {
                        target: content_id,
                        orientation: ControlOrientation::Vertical,
                        min_thumb_length: 20.0,
                    },
                    Node {
                        width: Px(scrollbar_width),
                        height: Percent(100.0),
                        ..default()
                    },
                    BackgroundColor(Color::srgba(0.15, 0.15, 0.15, 0.5)),
                ))
                .with_children(|sb| {
                    sb.spawn((
                        CoreScrollbarThumb,
                        Node {
                            width: Percent(100.0),
                            ..default()
                        },
                        BackgroundColor(Color::srgba(0.5, 0.5, 0.5, 0.8)),
                    ));
                });
        })
        .id()
}

/// A message that drives a refresh of the [`InspectorCache`].
///
/// This will cause the system sets [`CacheUpdate`] and [`SyncUI`] to run when seen,
/// via the use of run conditions added as part of [`InspectorWindowPlugin`](crate::gui::plugin::InspectorWindowPlugin).
///
/// This is a public message to allow users to trigger (or cancel!) refreshes manually if desired.
///
/// [`CacheUpdate`]: crate::gui::plugin::InspectorSet::CacheUpdate
/// [`SyncUI`]: crate::gui::plugin::InspectorSet::SyncUI
#[derive(Message)]
pub struct RefreshCache;

/// A message that drives a refresh of the UI panels,
/// without forcing a cache rebuild.
///
/// This will cause the system set [`Render`] to run.
///
/// [`Render`]: crate::gui::plugin::InspectorSet::Render

#[derive(Message)]
pub struct RefreshUI;

/// A system which periodically sends a [`RefreshCache`] message.
///
/// The frequency is controlled by the [`refresh_interval`] field in [`InspectorConfig`].
///
/// [`refresh_interval`]: InspectorConfig::refresh_interval
pub fn periodically_refresh_cache(
    mut message_writer: MessageWriter<RefreshCache>,
    time: Res<Time>,
    mut timer: Local<Timer>,
    mut is_timer_ticking: Local<bool>,
    config: Res<InspectorConfig>,
    state: Res<InspectorState>,
) {
    // Disable auto-refreshing in certain conditions.
    if config.refresh_interval.is_none() || state.is_paused {
        *is_timer_ticking = false;
        return;
    }

    // Initialize timer if needed
    if timer.duration().is_zero() {
        *timer = Timer::new(config.refresh_interval.unwrap(), TimerMode::Repeating);
    }

    if !*is_timer_ticking {
        *is_timer_ticking = true;
        timer.reset();
    }

    // Tick timer
    timer.tick(time.delta());

    // Send message if timer finished
    if timer.just_finished() {
        message_writer.write(RefreshCache);
    }
}
